# Generated by Django 4.2.30 on 2026-06-19 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai_jours', models.IntegerField()),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente signature'), ('signe', 'Signé'), ('en_cours', 'En cours'), ('livre', 'Livré'), ('valide', 'Validé'), ('annule', 'Annulé'), ('litige', 'En litige')], default='en_attente', max_length=20)),
                ('signe_client', models.BooleanField(default=False)),
                ('signe_freelance', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('conditions', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='contrats/')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ContratLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('accepte', models.BooleanField(null=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='api.contrat')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('lien', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categorie', models.CharField(max_length=100)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('video_presentation', models.URLField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('nb_ventes', models.IntegerField(default=0)),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='avis',
            name='cible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis_recus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avis',
            name='photos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='reponse_freelance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='bio_courte',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='disponibilite',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('partiel', 'Partiellement disponible'), ('indisponible', 'Indisponible')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='missions_completees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='nb_avis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='tarif_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='taux_reussite',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='titre_professionnel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='messages/fichiers/'),
        ),
        migrations.AddField(
            model_name='message',
            name='modifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='nom_fichier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='reponse_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='api.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='supprime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='taille_fichier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('texte', 'Texte'), ('image', 'Image'), ('video', 'Vidéo'), ('audio', 'Audio'), ('fichier', 'Fichier')], default='texte', max_length=10),
        ),
        migrations.AddField(
            model_name='mission',
            name='budget_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mission',
            name='competences_requises',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='freelance_assigne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_assignees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mission',
            name='nb_vues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='niveau_experience',
            field=models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('expert', 'Expert')], default='intermediaire', max_length=20),
        ),
        migrations.AddField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paiement',
            name='freelance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_freelance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('portefeuille', 'Portefeuille interne')], default='portefeuille', max_length=20),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='derniere_connexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='langue_interface',
            field=models.CharField(default='fr', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='pays',
            field=models.CharField(blank=True, default='Madagascar', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='couvertures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='avis',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='api.mission'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='api.mission'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('rembourse', 'Remboursé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('utilisateur', 'Utilisateur'), ('mission', 'Mission'), ('service', 'Service'), ('message', 'Message'), ('avis', 'Avis')], max_length=20)),
                ('raison', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('objet_id', models.IntegerField(blank=True, null=True)),
                ('signaleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai_jours', models.IntegerField()),
                ('nb_revisions', models.IntegerField(default=1)),
                ('fonctionnalites', models.TextField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='api.service')),
            ],
            options={
                'unique_together': {('service', 'niveau')},
            },
        ),
        migrations.CreateModel(
            name='ServiceGalerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=10)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='services/galerie/')),
                ('url', models.URLField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie', to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('reponse', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='api.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='freelance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PortfolioMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('pdf', 'PDF')], max_length=10)),
                ('fichier', models.FileField(upload_to='portfolio/medias/')),
                ('ordre', models.IntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='api.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='freelance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('message', 'Nouveau message'), ('candidature', 'Nouvelle candidature'), ('contrat', 'Contrat'), ('paiement', 'Paiement'), ('avis', 'Avis'), ('mission', 'Mission'), ('systeme', 'Système')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('lu', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MissionFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='missions/fichiers/')),
                ('nom_original', models.CharField(max_length=255)),
                ('taille', models.IntegerField(default=0)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='api.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=200)),
                ('entreprise', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('en_cours', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ContratLivraisonFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='livraisons/')),
                ('nom_original', models.CharField(max_length=255)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='api.contratlivraison')),
            ],
        ),
        migrations.AddField(
            model_name='contrat',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrat',
            name='freelance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_freelance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrat',
            name='mission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='api.mission'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='service_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.servicepackage'),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('organisme', models.CharField(max_length=200)),
                ('date_obtention', models.DateField()),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('lien', models.URLField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='api.categorie')),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='avis',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis', to='api.contrat'),
        ),
        migrations.AddField(
            model_name='avis',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='api.service'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='api.contrat'),
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('freelance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_en_favori', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favoris', to='api.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'service'), ('user', 'freelance')},
            },
        ),
    ]
